### PR TITLE
fix #367 - Fix boolean negative visiblityIf condition.

### LINKED ISSUE #367: VisibleIf - Negative condition case
A negative condition is not working with this example

```json
{
  "properties": {
    "consistent": {
      "type": "boolean",
      "widget": "checkbox"
    },
    "name": {
      "type": "string",
      "minLength": 1,
      "description": "Name",
      "title": "Name",
      "visibleIf": {
        "consistent": false
      }
    }
  }
}
```
But works when using an expression like `"$EXP$ !target.value"`

See [example at Stackblitz](https://stackblitz.com/edit/ngx-schema-form-template-visibleif-false-367)

### PR DESCRIPTION
**Pull request by daniele-pecora**
Also adds support for having '$EXP$'  conditions summed up in an array.

### CODE REVIEW

**Comment by ebrehault** [comment]
apparently there is a wrong dependency ```npm ERR! notarget No matching version found for @angular-devkit/schematics@11.0.1```

**Comment by daniele-pecora** [comment]
@ebrehault Would love to see this relased :-)

**Comment by ebrehault** [comment]
done :)

**Comment by daniele-pecora** [comment]
Thank you for quick action :-)

**Pull request merged**
