### PR TITLE
Fix 360 331 329

### PR DESCRIPTION
**Pull request by daniele-pecora**
Fixed issues 
#360 
#331 
#329

### CODE REVIEW

**Review by ebrehault — APPROVED** [review]

**Comment by develAman** [comment]
performance went down after the merge #364

**Comment by daniele-pecora** [comment]
> seems performance went down after the merge #364

Could you provide your schema that is having performance issue for analysis purpose?

**Comment by develAman** [comment]
@daniele-pecora sorry, it was combination of wrong schema and update version from 2.5.6 to 2.5.8
the main problem was wrongly generated schema(one array in the schema was not having oneOf in the items property)

**Comment by daniele-pecora** [comment]
>>I never thought that empty oneOf (oneOf: [ ]) will slow down the form building performance :)

I will check this.

**Pull request merged**
