### PR TITLE
Reset SchemaValidator

### PR DESCRIPTION
**Pull request by daniele-pecora**
…implementation

### CODE REVIEW

**Comment by fbessou** [comment]
Hi there :)
I suppose that z-schema use reference equality to lookup in its cache.
Wouldn't it be sufficient to create a new reference when parts of the schema are loaded ?
By using Object.assign for example.

```js
const schema = Object.assign({}, schema)
```

**Comment by daniele-pecora** [comment]
> Hi there :)
> I suppose that z-schema use reference equality to lookup in its cache.
> Wouldn't it be sufficient to create a new reference when parts of the schema are loaded ?
> By using Object.assign for example.
> 
> ```js
> const schema = Object.assign({}, schema)
> ```

Thank you for quick response :-)

The schema of the widget formProperty schema validates fine.

This issues occures with its parent-tree schemas.

Z-Schema holds a deep copy of every property's schema-part 
that has been validated once in an object.

For the key to a cache item it uses the schema object currently 
stored in the property's corresponding `widget.formProperty.schema`.

So updating `oneOf` by adding new items here will also update the key of the cache item.

But nevertheless I already did this and did it also on all its parent schemas,
and it cames out that it is not enough to make the key of the chache unrecognizable.

**Comment by daniele-pecora** [comment]
So I finally made it to create a stackblitz example for this.
https://stackblitz.com/edit/ngx-schema-form-primeng-validation-lazy-loading

Since `Z-Schema` and also `AJV´and I assume also other JSON Schema Validator do this, 
I still think that the option to reset the validator cache is significant is some way.

**Comment by ebrehault** [comment]
Sounds good to me

**Comment by karatashakan** [comment]
there is no problem and no error in widget component when I run the reset function of SchemaValidatorFactory. But onErrorChange output event of main sf-form component is still giving "['oneOf', 'an array with at least one element']" error.

**Pull request merged**
